# Generated by Django 4.2.2 on 2024-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarians',
            name='library',
            field=models.ManyToManyField(related_name='libraries', to='book.library'),
        ),
    ]
