# Generated by Django 4.2.2 on 2024-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_library_librarians_library_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='books_in_library',
            field=models.ManyToManyField(blank=True, related_name='lib_books', to='book.books'),
        ),
    ]
