# Generated by Django 4.2.2 on 2024-07-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_library_books_in_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_id',
        ),
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.ManyToManyField(related_name='books', to='book.author'),
        ),
    ]
